#!/usr/bin/with-contenv bash

# Set FileBot env variables

export "FILEBOT_OPTS=-Dapplication.deployment=docker -Dapplication.cache=/config/filebot/cache -Dapplication.dir=/config/filebot -Djava.io.tmpdir=/tmp/filebot -Dnet.filebot.archive.extractor=ShellExecutables -Dnet.filebot.license=/config/filebot/license.psm -Duser.home=/config/filebot"
  
# Fix some permissions:
chown -R ${PUID}:${PGID} \
        /usr/local/bin \
        /config \
		/filebot

exit