#!/usr/bin/with-contenv bash

# Set the license:
license=$(find /config/ -iname "*.psm" | head -n1)
if ! [ -z "${license}" ];
   then sh /filebot/filebot.sh --license=${license}
else
   echo -e "#####\n#\n#>> No license detected for FILEBOT.\n#>> Plz put you license psm file in /config/filebot folder\n#\n#\n#####"
fi

# Fix some permissions:
chown -R ${PUID}:${PGID} \
        /usr/local/bin \
        /config \
		/filebot

exit